### ISSUE TITLE
Can not reproduce the RAW files demo

### ISSUE THREAD

**Issue by erenRRDA** [mgharbi/demosaicnet_caffe#1]
I run the script of Processing RAW files:

python bin/demosaick --input data/test_raw_images/5d_mark_ii_iso800.tiff --output output --model pretrained_models/bayer --offset_x 1

but just get a noisy output image...
tried some other offset_x/y params, also didnot go well... 

BTW, the bayer_noise demo is good.

**Comment by tejasvnair** [comment]
Hi erenRRDA,

I am facing the same issue. Were you able to figure to find the issue and/or solution?

Thanks!

**Comment by mgharbi** [comment]
Hum strange, I just re-ran it with command you gave me and got a correct result. What's your environment? I might not have much time to look at it in the next two weeks, but I'll try if I have some spare cycles.

**Comment by mgharbi** [comment]
Maybe an issue with libtiff or some python imaging library? Could you send me your output by email?

**Comment by tejasvnair** [comment]
Thanks for your reply!

For me, the issue is with skimage.img_as_uint(). It creates a lot of noise.

In /bin/demosaick, while saving the output, for cases with groundtruth, it uses _float2uint() which works fine.
But for cases without groundtruth, skimage.img_as_uint() is used (for uint16). 

I replaced skimage.img_as_uint() with _float2uint() and it gives a much cleaner image.  Do you foresee any issues if _float2uint() is used instead?

I can't send you the output image (due to company restrictions). It could have made things easy...

**Comment by erenRRDA** [comment]
Hi, oracle85
 _float2uint() is also good for me.  Got the right image now. Thanks a lot!

Hi, mgharbi
I have uploaded the noisy image 5d_mark_ii_iso800_noisy.tiff here: 
 
https://drive.google.com/file/d/0B8Z-D3XPCWiqME1YRG1zSHpPNFU/view?usp=sharing

Hope you can figure it out. Thanks!

**Comment by tejasvnair** [comment]
Hi Michael,

How can I estimate the noise level (sigma) to be fed while testing on raw data captured from camera at different ISO levels?
Is there any method you recommend? Like a localized variance calculation?

**Comment by mgharbi** [comment]
@oracle85,

Foi et al. have some done thorough work on the topic, e.g. "Practical Poissonian-Gaussian noise modeling and
fitting for single-image raw-data" 

http://www.cs.tut.fi/~foi/sensornoise.html

**Comment by mgharbi** [comment]
@oracle85 and @erenRRDA, I'll look into the noise issue. But the image you send has clearly wrong black levels and posterization. I wonder if the library doesn't load the image as a 8-bits image. I'll add a 16-bits .png copy in the repo.

**Comment by mgharbi** [comment]
@oracle85: the only issue with _float2uint() is that the output will be 8-bits, even if your input was 16-bits

**Comment by mgharbi** [comment]
@erenRRDA: when you say the bayer_noise demo is good, do you mean running this command?

python bin/demosaick --input data/test_raw_images/5d_mark_ii_iso800.tiff --output output --model pretrained_models/**bayer_noise** --offset_x 1

**Comment by mgharbi** [comment]
I replaced the image I/O library  with opencv which should load and write tiff files correctly in 0623dd57a2f6e142f009a35f4fc4ef2bd5a70161.

If that does not work, try on this .png input and let me know what happens:
https://drive.google.com/open?id=0B3zPxG50pTVaWWlmcTdRcldwYWc

**Comment by tejasvnair** [comment]
Hi Michael,

With the updates (opencv), the output tiff file looks OK!
Thanks for your help.

**Comment by mgharbi** [comment]
Happy to help!
