### ISSUE TITLE
what raw formats are supported

### ISSUE THREAD

**Issue by ceciliavision** [mgharbi/demosaicnet_caffe#10]
Hi Michael,

I'm testing the demosaicnet on Sony raw file (.ARW). I used Libraw to generate .tiff bayer pattern, with the same command in your README: dcraw -T -d -W -6 {filename}

Then feed the .tiff file into the network. The output always looks greenish, seems to have a really bad white balance. I used Libraw to process that raw file: dcraw -T -o 0 -M -W -6 {filename}, and am able to get reasonable output.

Is it required to do pre-white balance to the bayer pattern?

Also, in your provided raw file, is that in linear color space?

Thanks for helping

**Comment by mgharbi** [comment]
Hi,

Yes the file should be linear provided you pass the right flag to libraw (-g 0 0 i believe). The network assumes the mosaic is already white balanced.

Best,

Mika
