### ISSUE TITLE
Convert Inference to OpenCV DNN

### ISSUE THREAD

**Issue by ghimiredhikura** [mgharbi/demosaicnet_caffe#11]
Hello, 

I am trying to convert forward pass network to opencv dnn module, but having difficulty in understanding some part of `demosaicnet/bin/demosaick` code. 

Can anyone please explain what this block of code actually does?

```ruby
def _make_mosaic(im, mosaic_type):
    if mosaic_type == 'bayer':
        layer = 'BayerMosaickLayer'
    elif mosaic_type == 'xtrans':
        layer = 'XTransMosaickLayer'
    else:
        raise Exception('Unknown mosaick type {}.'.format(mosaic_type))
    h, w, c = im.shape
    with tempfile.NamedTemporaryFile(mode='w+', delete=False) as f:
        f.write("""name: 'pythonnet' force_backward: true
        input: 'data' input_shape { dim:1 dim: %d dim: %d dim: %d }
        layer { type: 'Python' name: 'output' bottom: 'data' top: 'output'
          python_param { module: 'demosaicnet.layers' layer: '%s' } }""" % (c, h, w, layer))
        fname = f.name
    net = caffe.Net(fname, caffe.TEST)
    os.remove(fname)
    net.blobs['data'].data[...] = im.transpose([2, 0, 1])[...]
    out = np.squeeze(net.blobs['output'].data).transpose([1, 2, 0])
    net.forward()
    return out
```

**Comment by mgharbi** [comment]
Hey, this code just writes a PythonLayer wrapper on the fly, which is the Caffe interface to call a python function. The actual function code is here: https://github.com/mgharbi/demosaicnet/blob/efc56efc28eb767d0f368432d1cf46d5a6031f0f/demosaicnet/layers.py#L33

It essentially applies the Bayer or Xtrans mosaic mask to discard 2/3 of the color information.

Here's a pytorch implementation of the same thing: https://github.com/mgharbi/demosaicnet_torch/blob/554be8ea94783549173b0ed45a5b7ace69bc0eff/demosaic/dataset.py#L45

Hope this helps
