### ISSUE TITLE
Trouble installing requirements

### ISSUE THREAD

**Issue by rivaldo4t** [mgharbi/demosaicnet_caffe#13]
Hi,

I am having trouble installing the requirements. I am using conda 4.3.30 with Python 2.7.15. I tried the same with Python 3.6 too with same issue. 

When I enter `pip install -r requirements.txt`
I get -
`Collecting cv2==1.0 (from -r requirements.txt (line 4))
Could not find a version that satisfies the requirement cv2==1.0 (from -r requirements.txt (line 4)) (from versions: )
No matching distribution found for cv2==1.0 (from -r requirements.txt (line 4))`

I tried installing opencv-python before the requirements and tried running the requirement install command without the cv2==1.0 part. But a series of other errors showed up. 

Can you please let me know what I am doing wrong?

**Comment by rivaldo4t** [comment]
I [found](https://stackoverflow.com/a/55112034/3698992) that doing sudo apt install caffe-cpu on Ubuntu 18.04 compiles binding for python3 only. To get this code working, caffe is required for python2.7. 

So I followed [this](https://gist.github.com/nikitametha/c54e1abecff7ab53896270509da80215), installed opencv-python, scikit-image, numpy, scipy and tqdm separately on virtualenv, ran into some more [issues](https://gist.github.com/nikitametha/c54e1abecff7ab53896270509da80215#gistcomment-2859686) and was able to run this.

**Comment by mgharbi** [comment]
Thanks for posting your fix!
