### ISSUE TITLE
Issue while running demo

### ISSUE THREAD

**Issue by tejasvnair** [mgharbi/demosaicnet_caffe#2]
Hi Michael,

Thanks for sharing the code.

I tried running the demo (with noise)
 python bin/demosaick --input data/test_images/000001.png --output output --model pretrained_models/bayer_noise --noise 0.02

I get the following error 

ImportError: No module named demosaicnet.layers
Traceback (most recent call last):
  File "bin/demosaick", line 314, in <module>
    main(args)
  File "bin/demosaick", line 174, in main
    net = caffe.Net(arch_path, weights_path, caffe.TEST)
SystemError: NULL result without error in PyObject_Call

Any ideas what maybe going wrong here?

Thanks,
Tejas

**Comment by tejasvnair** [comment]
Got it to work by updating the python path. Closing the issue.

**Comment by pramodkasulanati** [comment]
Can please share the changes you have made as I am also facing same error
Error: -
ModuleNotFoundError: No module named 'demosaicnet'
Traceback (most recent call last):
  File "bin/demosaick", line 344, in <module>
    main(args)
  File "bin/demosaick", line 190, in main
    net = caffe.Net(arch_path, weights_path, caffe.TEST)
SystemError: <Boost.Python.function object at 0x2135180> returned NULL without setting an error

**Comment by mgharbi** [comment]
Please make sure the subfolder demosaicnet is in your Python path, eg using the PYTHONPATH env var.

Mika

**Comment by pramodkasulanati** [comment]
I have done this export PYTHONPATH=$PYTHONPATH:"$PWD/demosaicnet" but still getting the same error

**Comment by mgharbi** [comment]
I assume $PWD referes to the root of the repo? That is PWD=some/path/to/demosaicnet that contains a subfolder (also called demosaicnet), which is the actual python package correct?

Michael
