### ISSUE TITLE
training input raw and output raw

### ISSUE THREAD

**Issue by csu-qwjy** [mgharbi/demosaicnet_caffe#4]
Thank you very much for the ingenious network model put forward by the author. 
I trained to network for input raw and output raw. The output of the raw image into RGB images, there is a serious blur, and there is color deviation. Attempts at various methods still fail to solve the problem. What good solution does the you have?

**Comment by mgharbi** [comment]
I am not sure I understand your problem, could you be more specific? What do you mean by input/output raw? You might want to check your images are normalized to [0,1] for training
