### ISSUE TITLE
Data Loading

### ISSUE THREAD

**Issue by Tuan-cat** [mgharbi/demosaicnet_caffe#6]
Hello,
I have run 'download_dataset.py' and downloaded all files. But failed to zip them.
I don't know where the problem is.

**Comment by my1347** [comment]
try again and agian ,you will finally get it done,I have tried about 30 times

**Comment by wangc16** [comment]
Let me try.

**Comment by Tuan-cat** [comment]
Let me try. thank you

**Comment by mgharbi** [comment]
the links should be repaired now
