### ISSUE TITLE
About bayer type

### ISSUE THREAD

**Issue by ghost** [mgharbi/demosaicnet_caffe#9]
hi , in ur code ,u only support bayer type GRBG ,  but when testing with MSR Dataset ,its bayer type is RGGB , so i should modify ur PackBayerMosaicLayer to support this or i can just use ur defalut layer ?

or i need to train this model on that dataset ?

in ur paper ,u pretrained ur mode on imagenet data ,and it seems u asume all the image ofrom that dataset have the same bayer type GRBG ?

**Comment by mgharbi** [comment]
shift 1 pixel right and down
